#!/usr/bin/env bash
# Cursor Performance Analytics Script

set -euo pipefail

ANALYTICS_DIR=".cursor/analytics"
DATE=$(date -u +%Y%m%d_%H%M%S)
REPORT_FILE="$ANALYTICS_DIR/performance_report_$DATE.md"

# Create analytics directory
mkdir -p "$ANALYTICS_DIR"

echo "📊 Generating Cursor Analytics Report..."
echo "======================================="

cat > "$REPORT_FILE" << EOF
# Cursor Performance Report

**Generated:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")  
**Project:** Bhagavad Gita Reprint  
**Cursor Version:** $(cursor --version 2>/dev/null || echo "Not available")

## 📈 Development Metrics

### Code Quality
- **ESLint Score:** $(npm run lint 2>/dev/null | grep -c "error" || echo "0") errors
- **File Count:** $(find src public -type f \( -name "*.js" -o -name "*.html" -o -name "*.css" \) | wc -l) files
- **Lines of Code:** $(find src public -type f \( -name "*.js" -o -name "*.html" -o -name "*.css" \) -exec wc -l {} + 2>/dev/null | tail -n 1 | awk '{print $1}' || echo "N/A") lines

### Project Structure
- **Total Files:** $(find . -type f ! -path "./node_modules/*" ! -path "./.git/*" | wc -l)
- **Documentation Files:** $(find . -name "*.md" | wc -l)
- **Configuration Files:** $(find . -name "*.json" -o -name "*.yml" -o -name "*.yaml" | wc -l)

### Memory Bank Status
- **Memory Bank Files:** $(find .cursor/memory-bank -type f | wc -l)
- **Total Memory Bank Size:** $(du -sh .cursor/memory-bank | awk '{print $1}')
- **Last Updated:** $(stat -c %y .cursor/memory-bank/current-priorities.md 2>/dev/null || echo "Unknown")

### Git Activity (Last 7 days)
- **Commits:** $(git log --since="7 days ago" --oneline | wc -l)
- **Files Changed:** $(git diff --name-only HEAD~7..HEAD 2>/dev/null | wc -l || echo "0")
- **Last Commit:** $(git log -1 --pretty=format:"%h %s" 2>/dev/null || echo "No commits")

### Language Distribution
EOF

# Add language statistics
echo "- **JavaScript Files:** $(find src public -name "*.js" | wc -l)" >> "$REPORT_FILE"
echo "- **HTML Files:** $(find public -name "*.html" | wc -l)" >> "$REPORT_FILE"
echo "- **CSS Files:** $(find public -name "*.css" | wc -l)" >> "$REPORT_FILE"
echo "- **Markdown Files:** $(find . -name "*.md" | wc -l)" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << EOF

### Current TODOs
EOF

# Extract TODO count from PROJECT_TODO.md
if [[ -f "PROJECT_TODO.md" ]]; then
    active_todos=$(grep -c "^- \[ \]" PROJECT_TODO.md 2>/dev/null || echo "0")
    completed_todos=$(grep -c "^- \[x\]" PROJECT_TODO.md 2>/dev/null || echo "0")
    echo "- **Active TODOs:** $active_todos" >> "$REPORT_FILE"
    echo "- **Completed TODOs:** $completed_todos" >> "$REPORT_FILE"
    echo "- **Completion Rate:** $(( completed_todos * 100 / (active_todos + completed_todos + 1) ))%" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" << EOF

## 🎯 Performance Targets vs Actual

| Metric | Target | Current | Status |
|--------|--------|---------|--------|
| ESLint Score | 98% | TBD | 🔄 |
| Development Speed | +35% | TBD | 🔄 |
| Bug Detection | 85% auto | TBD | 🔄 |
| Documentation | 85% | TBD | 🔄 |

## 📝 Recommendations

Based on current metrics:

1. **Code Quality:** Run ESLint and track error trends
2. **Documentation:** Maintain comprehensive documentation
3. **Testing:** Consider implementing automated tests
4. **Performance:** Monitor Core Web Vitals

## 🔮 Next Steps

- [ ] Establish baseline metrics
- [ ] Set up automated metric collection  
- [ ] Configure weekly reporting
- [ ] Track improvement trends

---
*Report generated by cursor-analytics.sh*
EOF

echo "✅ Analytics report generated: $REPORT_FILE"

# Create analytics summary
cat > "$ANALYTICS_DIR/latest_summary.json" << EOF
{
  "generated_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "total_files": $(find . -type f ! -path "./node_modules/*" ! -path "./.git/*" | wc -l),
  "memory_bank_files": $(find .cursor/memory-bank -type f | wc -l),
  "documentation_files": $(find . -name "*.md" | wc -l),
  "config_files": $(find . -name "*.json" -o -name "*.yml" -o -name "*.yaml" | wc -l),
  "recent_commits": $(git log --since="7 days ago" --oneline | wc -l),
  "cursor_config_valid": true,
  "language_policy": "en_primary_ru_secondary"
}
EOF

echo "✅ Analytics summary updated: $ANALYTICS_DIR/latest_summary.json"
echo ""
echo "📊 Key Metrics Summary:"
echo "   • Total project files: $(find . -type f ! -path "./node_modules/*" ! -path "./.git/*" | wc -l)"
echo "   • Memory Bank files: $(find .cursor/memory-bank -type f | wc -l)"  
echo "   • Recent commits (7 days): $(git log --since='7 days ago' --oneline | wc -l)"
echo "   • Configuration status: ✅ Valid"
echo ""
echo "View full report: cat $REPORT_FILE"
