name: Cleanup Actions queue

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

concurrency:
  group: cleanup-actions-queue
  cancel-in-progress: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel/Delete queued and in_progress runs of self-hosted workflow
        id: sweep
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            // Target workflow by file name
            const workflow_id = 'deploy.yml';
            const statuses = ['queued', 'in_progress'];
            let canceled = 0, deleted = 0, failed = 0;
            for (const status of statuses) {
              for (let page = 1; page <= 20; page++) {
                const { data } = await github.rest.actions.listWorkflowRuns({
                  owner,
                  repo,
                  workflow_id,
                  status,
                  per_page: 100,
                  page
                });
                const runs = data.workflow_runs || [];
                if (runs.length === 0) break;
                for (const run of runs) {
                  try {
                    if (status === 'queued') {
                      await github.rest.actions.deleteWorkflowRun({ owner, repo, run_id: run.id });
                      deleted++;
                    } else {
                      await github.rest.actions.cancelWorkflowRun({ owner, repo, run_id: run.id });
                      canceled++;
                    }
                  } catch (e) {
                    failed++;
                  }
                }
                if (runs.length < 100) break;
              }
            }
            core.setOutput('summary', JSON.stringify({ canceled, deleted, failed }));
      - name: Print result
        run: echo "${{ steps.sweep.outputs.summary }}"