name: Deploy to GitHub Pages (self-hosted, disabled)

on:
  workflow_dispatch:

concurrency:
  group: self-hosted-deploy
  cancel-in-progress: true

jobs:
  deploy:
    if: false
    runs-on: self-hosted  # <--- Добавьте эту строку
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace Formspree ID
        env:
          FORM_ID: ${{ secrets.FORM_ID }}
        run: |
          sed -i "s/{{FORM_ID}}/$FORM_ID/g" public/contacts.html

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
