name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted  # <--- Добавьте эту строку
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace Formspree ID
        env:
          FORM_ID: ${{ secrets.FORM_ID }}
        run: |
          sed -i "s/{{FORM_ID}}/$FORM_ID/g" public/contacts.html

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
